plugins:
  brakeman:
    enabled: true
    check:
      cross_site_scripting:
        enabled: false
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - ruby
    exclude_paths:
      - 'app/controllers/'
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-79
    checks:
      Rubocop/Style/Documentation:
        enabled: false
      Rubocop/Layout/LineLength:
        enabled: false
      Rubocop/Style/FrozenStringLiteralComment:
        enabled: false
      Rubocop/Metrics/BlockLength:
        enabled: false
ratings:
  paths:
    - 'app/**'
    - 'lib/**'
exclude_paths:
  - 'config/'
  - 'db/'
  - 'public/'
  - 'spec/'
  - 'vendor/'
  - 'bin/'
