company_info:
  website: 'https://goldenowl.asia'
  address: '538, CMT8 Street, Ward 11, District 3, HCMC, Vietnam'
  address_map_url: 'https://www.google.com/maps/place/Ward+11,+538+C%C3%A1ch+M%E1%BA%A1ng+Th%C3%A1ng+8,+ph%C6%B0%E1%BB%9Dng+11,+Qu%E1%BA%ADn+3,+H%E1%BB%93+Ch%C3%AD+Minh/@10.780231,106.6645121,15z/data=!3m1!4b1!4m2!3m1!1s0x31752ed22b5f8907:0xda91b3a0b76a6f36'
  linkedin_url: 'https://www.linkedin.com/organization-guest/company/golden-owl-consulting?challengeId=AQHAKkIhIDL6ZQAAAXNb3A6TWdfilvu5uzgfKpdRHqbTSNT_MAji0d7O4XDYBcfKiVsiiMP9_eNtSyD1teXirqZNzHHFMQd_0Q&submissionId=ae1b8f7e-6a7c-2216-91b4-f47ea6168a50'
  facebook_url: 'https://www.facebook.com/goldenowl.asia/'
  twitter_url: 'https://twitter.com/goldenowlasia?lang=en'
  career_url: 'https://golden-owl-web.herokuapp.com/careers/details/'
  blog_url: 'https://golden-owl-web.herokuapp.com/blog/details/'
